queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Checks
      - check-success=Licenses (models)
      - check-success=Licenses (consumer)
      - check-success=Licenses (commands)
      - check-success=Unit tests (3.7, models)
      - check-success=Unit tests (3.7, consumer)
      - check-success=Unit tests (3.7, commands)
      - check-success=Unit tests (3.8, models)
      - check-success=Unit tests (3.8, consumer)
      - check-success=Unit tests (3.8, commands)
      - check-success=Unit tests (3.9, models)
      - check-success=Unit tests (3.9, consumer)
      - check-success=Unit tests (3.9, commands)


pull_request_rules:

- name: Automatic merge on approval
  actions:
    queue:
      name: default
      method: rebase
      rebase_fallback: none
  conditions:
    - label!=no-mergify
    - -draft
    - approved-reviews-by=@fedora-infra/data-team
    - "#changes-requested-reviews-by=0"
    - check-success=Checks
    - check-success=Licenses (models)
    - check-success=Licenses (consumer)
    - check-success=Licenses (commands)
    - check-success=Unit tests (3.7, models)
    - check-success=Unit tests (3.7, consumer)
    - check-success=Unit tests (3.7, commands)
    - check-success=Unit tests (3.8, models)
    - check-success=Unit tests (3.8, consumer)
    - check-success=Unit tests (3.8, commands)
    - check-success=Unit tests (3.9, models)
    - check-success=Unit tests (3.9, consumer)
    - check-success=Unit tests (3.9, commands)

- name: Automatic merge Dependabot PRs
  actions:
    queue:
      name: default
      method: rebase
      rebase_fallback: none
  conditions:
    - label!=no-mergify
    - -draft
    - author=dependabot[bot]
    - approved-reviews-by=github-actions[bot]
    - "#changes-requested-reviews-by=0"
    - check-success=Checks
    - check-success=Licenses (models)
    - check-success=Licenses (consumer)
    - check-success=Licenses (commands)
    - check-success=Unit tests (3.7, models)
    - check-success=Unit tests (3.7, consumer)
    - check-success=Unit tests (3.7, commands)
    - check-success=Unit tests (3.8, models)
    - check-success=Unit tests (3.8, consumer)
    - check-success=Unit tests (3.8, commands)
    - check-success=Unit tests (3.9, models)
    - check-success=Unit tests (3.9, consumer)
    - check-success=Unit tests (3.9, commands)
