language: python
python:
 - "2.7"
 - "3.6"
install: ./.travis-dev-setup.sh
script: ./.travis-runtests.sh
notifications:
    email: false
    irc:
        - "irc.freenode.net#fedora-apps"
    on_success: change
    on_failure: change
